// Code generated by "stringer -type=CmdType"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IRREGAL-0]
	_ = x[STACK_PUSH-1]
	_ = x[STACK_DUP-2]
	_ = x[STACK_SWAP-3]
	_ = x[STACK_DROP-4]
	_ = x[STACK_DUP_N-5]
	_ = x[STACK_SLIDE_N-6]
	_ = x[ARITH_ADD-7]
	_ = x[ARITH_SUB-8]
	_ = x[ARITH_MUL-9]
	_ = x[ARITH_DIV-10]
	_ = x[ARITH_MOD-11]
	_ = x[HEAP_STORE-12]
	_ = x[HEAP_LOAD-13]
	_ = x[FLOW_LABEL-14]
	_ = x[FLOW_GOSUB-15]
	_ = x[FLOW_JUMP-16]
	_ = x[FLOW_BEZ-17]
	_ = x[FLOW_BLTZ-18]
	_ = x[FLOW_ENDSUB-19]
	_ = x[FLOW_HALT-20]
	_ = x[IO_PUTCHAR-21]
	_ = x[IO_PUTNUM-22]
	_ = x[IO_READCHAR-23]
	_ = x[IO_READNUM-24]
}

const _CmdType_name = "IRREGALSTACK_PUSHSTACK_DUPSTACK_SWAPSTACK_DROPSTACK_DUP_NSTACK_SLIDE_NARITH_ADDARITH_SUBARITH_MULARITH_DIVARITH_MODHEAP_STOREHEAP_LOADFLOW_LABELFLOW_GOSUBFLOW_JUMPFLOW_BEZFLOW_BLTZFLOW_ENDSUBFLOW_HALTIO_PUTCHARIO_PUTNUMIO_READCHARIO_READNUM"

var _CmdType_index = [...]uint8{0, 7, 17, 26, 36, 46, 57, 70, 79, 88, 97, 106, 115, 125, 134, 144, 154, 163, 171, 180, 191, 200, 210, 219, 230, 240}

func (i CmdType) String() string {
	if i < 0 || i >= CmdType(len(_CmdType_index)-1) {
		return "CmdType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CmdType_name[_CmdType_index[i]:_CmdType_index[i+1]]
}
